# WS ASYNC SERVER
SERVER_PORT = 5060
SERVER_IP = "0.0.0.0"
#### HTTP PRODUCER
SERVICE_IP = "127.0.0.1"
SERVICE_PORT = 8000
##### CLIENT
CLIENT_ID = ""
ACCES_TOKEN = ""
CLIENT_TYPE = "" # Consumer or producer